version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:8000:8000
    links:
      - redis:redis
    depends_on:
      - redis
    command: "dockerize 
    -wait tcp://redis:6379 
    -timeout 60s 
    /opt/IBIS_creator/startup.sh"
    restart: unless-stopped
    volumes:
      - staticdata: /opt/IBIS_creator/static
      - secretfiles: /opt/IBIS_creator/SECRET_FILES
      - ./local_settings.json:/opt/IBIS_creator/SECRET_FILES/local_settings.json
  redis:
    image: redis:5-alpine3.9
    restart: unless-stopped

volumes:
  staticdata:
  secretfiles:
