version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - redis:redis
    depends_on:
      - redis
    command: "dockerize 
    -wait tcp://redis:6379 
    -timeout 60s 
    ./startup.sh"
    restart: unless-stopped
    volumes:
      - staticdata:/opt/IBIS_creator/static 
      - ./SECRET_FILES:/opt/IBIS_creator/SECRET_FILES
  redis:
    image: redis:5-alpine3.9
    restart: unless-stopped
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    restart: unless-stopped
    links:
      - app:ibiscreator
    depends_on:
      - app
    volumes:
      - staticdata:/static
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 127.0.0.1:8000:8000
    
volumes:
  staticdata:
  
